#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexiSqlTools.Core
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MasterDataBase")]
	public partial class MasterDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public MasterDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MasterDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MasterDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MasterDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<sys_Database> sys_Databases
		{
			get
			{
				return this.GetTable<sys_Database>();
			}
		}
		
		public System.Data.Linq.Table<sys_Database1> sys_Database1s
		{
			get
			{
				return this.GetTable<sys_Database1>();
			}
		}
		
		public System.Data.Linq.Table<sys_Object> sys_Objects
		{
			get
			{
				return this.GetTable<sys_Object>();
			}
		}
		
		public System.Data.Linq.Table<INFORMATION_SCHEMA_COLUMN> INFORMATION_SCHEMA_COLUMNs
		{
			get
			{
				return this.GetTable<INFORMATION_SCHEMA_COLUMN>();
			}
		}
		
		public System.Data.Linq.Table<sys_Type> sys_Types
		{
			get
			{
				return this.GetTable<sys_Type>();
			}
		}
		
		public System.Data.Linq.Table<sys_All_column> sys_All_columns
		{
			get
			{
				return this.GetTable<sys_All_column>();
			}
		}
		
		public System.Data.Linq.Table<sys_Index_column> sys_Index_columns
		{
			get
			{
				return this.GetTable<sys_Index_column>();
			}
		}
		
		public System.Data.Linq.Table<vw_SPGenenerator> vw_SPGenenerators
		{
			get
			{
				return this.GetTable<vw_SPGenenerator>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sys_Databases")]
	public partial class sys_Database
	{
		
		private string _name;
		
		private int _database_id;
		
		private System.Nullable<int> _source_database_id;
		
		private System.Data.Linq.Binary _owner_sid;
		
		private System.DateTime _create_date;
		
		private System.Nullable<byte> _compatibility_level;
		
		private string _collation_name;
		
		private System.Nullable<byte> _user_access;
		
		private string _user_access_desc;
		
		private System.Nullable<bool> _is_read_only;
		
		private bool _is_auto_close_on;
		
		private System.Nullable<bool> _is_auto_shrink_on;
		
		private System.Nullable<byte> _state;
		
		private string _state_desc;
		
		private System.Nullable<bool> _is_in_standby;
		
		private System.Nullable<bool> _is_cleanly_shutdown;
		
		private System.Nullable<bool> _is_supplemental_logging_enabled;
		
		private System.Nullable<byte> _snapshot_isolation_state;
		
		private string _snapshot_isolation_state_desc;
		
		private System.Nullable<bool> _is_read_committed_snapshot_on;
		
		private System.Nullable<byte> _recovery_model;
		
		private string _recovery_model_desc;
		
		private System.Nullable<byte> _page_verify_option;
		
		private string _page_verify_option_desc;
		
		private System.Nullable<bool> _is_auto_create_stats_on;
		
		private System.Nullable<bool> _is_auto_update_stats_on;
		
		private System.Nullable<bool> _is_auto_update_stats_async_on;
		
		private System.Nullable<bool> _is_ansi_null_default_on;
		
		private System.Nullable<bool> _is_ansi_nulls_on;
		
		private System.Nullable<bool> _is_ansi_padding_on;
		
		private System.Nullable<bool> _is_ansi_warnings_on;
		
		private System.Nullable<bool> _is_arithabort_on;
		
		private System.Nullable<bool> _is_concat_null_yields_null_on;
		
		private System.Nullable<bool> _is_numeric_roundabort_on;
		
		private System.Nullable<bool> _is_quoted_identifier_on;
		
		private System.Nullable<bool> _is_recursive_triggers_on;
		
		private System.Nullable<bool> _is_cursor_close_on_commit_on;
		
		private System.Nullable<bool> _is_local_cursor_default;
		
		private System.Nullable<bool> _is_fulltext_enabled;
		
		private System.Nullable<bool> _is_trustworthy_on;
		
		private System.Nullable<bool> _is_db_chaining_on;
		
		private System.Nullable<bool> _is_parameterization_forced;
		
		private bool _is_master_key_encrypted_by_server;
		
		private bool _is_published;
		
		private bool _is_subscribed;
		
		private bool _is_merge_published;
		
		private bool _is_distributor;
		
		private bool _is_sync_with_backup;
		
		private System.Guid _service_broker_guid;
		
		private bool _is_broker_enabled;
		
		private System.Nullable<byte> _log_reuse_wait;
		
		private string _log_reuse_wait_desc;
		
		private System.Nullable<bool> _is_date_correlation_on;
		
		public sys_Database()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_database_id", DbType="Int NOT NULL")]
		public int database_id
		{
			get
			{
				return this._database_id;
			}
			set
			{
				if ((this._database_id != value))
				{
					this._database_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_source_database_id", DbType="Int")]
		public System.Nullable<int> source_database_id
		{
			get
			{
				return this._source_database_id;
			}
			set
			{
				if ((this._source_database_id != value))
				{
					this._source_database_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_owner_sid", DbType="VarBinary(85)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary owner_sid
		{
			get
			{
				return this._owner_sid;
			}
			set
			{
				if ((this._owner_sid != value))
				{
					this._owner_sid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_date", DbType="DateTime NOT NULL")]
		public System.DateTime create_date
		{
			get
			{
				return this._create_date;
			}
			set
			{
				if ((this._create_date != value))
				{
					this._create_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_compatibility_level", DbType="TinyInt")]
		public System.Nullable<byte> compatibility_level
		{
			get
			{
				return this._compatibility_level;
			}
			set
			{
				if ((this._compatibility_level != value))
				{
					this._compatibility_level = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_collation_name", DbType="NVarChar(128)")]
		public string collation_name
		{
			get
			{
				return this._collation_name;
			}
			set
			{
				if ((this._collation_name != value))
				{
					this._collation_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_access", DbType="TinyInt")]
		public System.Nullable<byte> user_access
		{
			get
			{
				return this._user_access;
			}
			set
			{
				if ((this._user_access != value))
				{
					this._user_access = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_access_desc", DbType="NVarChar(60)")]
		public string user_access_desc
		{
			get
			{
				return this._user_access_desc;
			}
			set
			{
				if ((this._user_access_desc != value))
				{
					this._user_access_desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_read_only", DbType="Bit")]
		public System.Nullable<bool> is_read_only
		{
			get
			{
				return this._is_read_only;
			}
			set
			{
				if ((this._is_read_only != value))
				{
					this._is_read_only = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_auto_close_on", DbType="Bit NOT NULL")]
		public bool is_auto_close_on
		{
			get
			{
				return this._is_auto_close_on;
			}
			set
			{
				if ((this._is_auto_close_on != value))
				{
					this._is_auto_close_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_auto_shrink_on", DbType="Bit")]
		public System.Nullable<bool> is_auto_shrink_on
		{
			get
			{
				return this._is_auto_shrink_on;
			}
			set
			{
				if ((this._is_auto_shrink_on != value))
				{
					this._is_auto_shrink_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="TinyInt")]
		public System.Nullable<byte> state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this._state = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state_desc", DbType="NVarChar(60)")]
		public string state_desc
		{
			get
			{
				return this._state_desc;
			}
			set
			{
				if ((this._state_desc != value))
				{
					this._state_desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_in_standby", DbType="Bit")]
		public System.Nullable<bool> is_in_standby
		{
			get
			{
				return this._is_in_standby;
			}
			set
			{
				if ((this._is_in_standby != value))
				{
					this._is_in_standby = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_cleanly_shutdown", DbType="Bit")]
		public System.Nullable<bool> is_cleanly_shutdown
		{
			get
			{
				return this._is_cleanly_shutdown;
			}
			set
			{
				if ((this._is_cleanly_shutdown != value))
				{
					this._is_cleanly_shutdown = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_supplemental_logging_enabled", DbType="Bit")]
		public System.Nullable<bool> is_supplemental_logging_enabled
		{
			get
			{
				return this._is_supplemental_logging_enabled;
			}
			set
			{
				if ((this._is_supplemental_logging_enabled != value))
				{
					this._is_supplemental_logging_enabled = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_snapshot_isolation_state", DbType="TinyInt")]
		public System.Nullable<byte> snapshot_isolation_state
		{
			get
			{
				return this._snapshot_isolation_state;
			}
			set
			{
				if ((this._snapshot_isolation_state != value))
				{
					this._snapshot_isolation_state = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_snapshot_isolation_state_desc", DbType="NVarChar(60)")]
		public string snapshot_isolation_state_desc
		{
			get
			{
				return this._snapshot_isolation_state_desc;
			}
			set
			{
				if ((this._snapshot_isolation_state_desc != value))
				{
					this._snapshot_isolation_state_desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_read_committed_snapshot_on", DbType="Bit")]
		public System.Nullable<bool> is_read_committed_snapshot_on
		{
			get
			{
				return this._is_read_committed_snapshot_on;
			}
			set
			{
				if ((this._is_read_committed_snapshot_on != value))
				{
					this._is_read_committed_snapshot_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recovery_model", DbType="TinyInt")]
		public System.Nullable<byte> recovery_model
		{
			get
			{
				return this._recovery_model;
			}
			set
			{
				if ((this._recovery_model != value))
				{
					this._recovery_model = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recovery_model_desc", DbType="NVarChar(60)")]
		public string recovery_model_desc
		{
			get
			{
				return this._recovery_model_desc;
			}
			set
			{
				if ((this._recovery_model_desc != value))
				{
					this._recovery_model_desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_page_verify_option", DbType="TinyInt")]
		public System.Nullable<byte> page_verify_option
		{
			get
			{
				return this._page_verify_option;
			}
			set
			{
				if ((this._page_verify_option != value))
				{
					this._page_verify_option = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_page_verify_option_desc", DbType="NVarChar(60)")]
		public string page_verify_option_desc
		{
			get
			{
				return this._page_verify_option_desc;
			}
			set
			{
				if ((this._page_verify_option_desc != value))
				{
					this._page_verify_option_desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_auto_create_stats_on", DbType="Bit")]
		public System.Nullable<bool> is_auto_create_stats_on
		{
			get
			{
				return this._is_auto_create_stats_on;
			}
			set
			{
				if ((this._is_auto_create_stats_on != value))
				{
					this._is_auto_create_stats_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_auto_update_stats_on", DbType="Bit")]
		public System.Nullable<bool> is_auto_update_stats_on
		{
			get
			{
				return this._is_auto_update_stats_on;
			}
			set
			{
				if ((this._is_auto_update_stats_on != value))
				{
					this._is_auto_update_stats_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_auto_update_stats_async_on", DbType="Bit")]
		public System.Nullable<bool> is_auto_update_stats_async_on
		{
			get
			{
				return this._is_auto_update_stats_async_on;
			}
			set
			{
				if ((this._is_auto_update_stats_async_on != value))
				{
					this._is_auto_update_stats_async_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_ansi_null_default_on", DbType="Bit")]
		public System.Nullable<bool> is_ansi_null_default_on
		{
			get
			{
				return this._is_ansi_null_default_on;
			}
			set
			{
				if ((this._is_ansi_null_default_on != value))
				{
					this._is_ansi_null_default_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_ansi_nulls_on", DbType="Bit")]
		public System.Nullable<bool> is_ansi_nulls_on
		{
			get
			{
				return this._is_ansi_nulls_on;
			}
			set
			{
				if ((this._is_ansi_nulls_on != value))
				{
					this._is_ansi_nulls_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_ansi_padding_on", DbType="Bit")]
		public System.Nullable<bool> is_ansi_padding_on
		{
			get
			{
				return this._is_ansi_padding_on;
			}
			set
			{
				if ((this._is_ansi_padding_on != value))
				{
					this._is_ansi_padding_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_ansi_warnings_on", DbType="Bit")]
		public System.Nullable<bool> is_ansi_warnings_on
		{
			get
			{
				return this._is_ansi_warnings_on;
			}
			set
			{
				if ((this._is_ansi_warnings_on != value))
				{
					this._is_ansi_warnings_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_arithabort_on", DbType="Bit")]
		public System.Nullable<bool> is_arithabort_on
		{
			get
			{
				return this._is_arithabort_on;
			}
			set
			{
				if ((this._is_arithabort_on != value))
				{
					this._is_arithabort_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_concat_null_yields_null_on", DbType="Bit")]
		public System.Nullable<bool> is_concat_null_yields_null_on
		{
			get
			{
				return this._is_concat_null_yields_null_on;
			}
			set
			{
				if ((this._is_concat_null_yields_null_on != value))
				{
					this._is_concat_null_yields_null_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_numeric_roundabort_on", DbType="Bit")]
		public System.Nullable<bool> is_numeric_roundabort_on
		{
			get
			{
				return this._is_numeric_roundabort_on;
			}
			set
			{
				if ((this._is_numeric_roundabort_on != value))
				{
					this._is_numeric_roundabort_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_quoted_identifier_on", DbType="Bit")]
		public System.Nullable<bool> is_quoted_identifier_on
		{
			get
			{
				return this._is_quoted_identifier_on;
			}
			set
			{
				if ((this._is_quoted_identifier_on != value))
				{
					this._is_quoted_identifier_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_recursive_triggers_on", DbType="Bit")]
		public System.Nullable<bool> is_recursive_triggers_on
		{
			get
			{
				return this._is_recursive_triggers_on;
			}
			set
			{
				if ((this._is_recursive_triggers_on != value))
				{
					this._is_recursive_triggers_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_cursor_close_on_commit_on", DbType="Bit")]
		public System.Nullable<bool> is_cursor_close_on_commit_on
		{
			get
			{
				return this._is_cursor_close_on_commit_on;
			}
			set
			{
				if ((this._is_cursor_close_on_commit_on != value))
				{
					this._is_cursor_close_on_commit_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_local_cursor_default", DbType="Bit")]
		public System.Nullable<bool> is_local_cursor_default
		{
			get
			{
				return this._is_local_cursor_default;
			}
			set
			{
				if ((this._is_local_cursor_default != value))
				{
					this._is_local_cursor_default = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_fulltext_enabled", DbType="Bit")]
		public System.Nullable<bool> is_fulltext_enabled
		{
			get
			{
				return this._is_fulltext_enabled;
			}
			set
			{
				if ((this._is_fulltext_enabled != value))
				{
					this._is_fulltext_enabled = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_trustworthy_on", DbType="Bit")]
		public System.Nullable<bool> is_trustworthy_on
		{
			get
			{
				return this._is_trustworthy_on;
			}
			set
			{
				if ((this._is_trustworthy_on != value))
				{
					this._is_trustworthy_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_db_chaining_on", DbType="Bit")]
		public System.Nullable<bool> is_db_chaining_on
		{
			get
			{
				return this._is_db_chaining_on;
			}
			set
			{
				if ((this._is_db_chaining_on != value))
				{
					this._is_db_chaining_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_parameterization_forced", DbType="Bit")]
		public System.Nullable<bool> is_parameterization_forced
		{
			get
			{
				return this._is_parameterization_forced;
			}
			set
			{
				if ((this._is_parameterization_forced != value))
				{
					this._is_parameterization_forced = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_master_key_encrypted_by_server", DbType="Bit NOT NULL")]
		public bool is_master_key_encrypted_by_server
		{
			get
			{
				return this._is_master_key_encrypted_by_server;
			}
			set
			{
				if ((this._is_master_key_encrypted_by_server != value))
				{
					this._is_master_key_encrypted_by_server = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_published", DbType="Bit NOT NULL")]
		public bool is_published
		{
			get
			{
				return this._is_published;
			}
			set
			{
				if ((this._is_published != value))
				{
					this._is_published = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_subscribed", DbType="Bit NOT NULL")]
		public bool is_subscribed
		{
			get
			{
				return this._is_subscribed;
			}
			set
			{
				if ((this._is_subscribed != value))
				{
					this._is_subscribed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_merge_published", DbType="Bit NOT NULL")]
		public bool is_merge_published
		{
			get
			{
				return this._is_merge_published;
			}
			set
			{
				if ((this._is_merge_published != value))
				{
					this._is_merge_published = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_distributor", DbType="Bit NOT NULL")]
		public bool is_distributor
		{
			get
			{
				return this._is_distributor;
			}
			set
			{
				if ((this._is_distributor != value))
				{
					this._is_distributor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_sync_with_backup", DbType="Bit NOT NULL")]
		public bool is_sync_with_backup
		{
			get
			{
				return this._is_sync_with_backup;
			}
			set
			{
				if ((this._is_sync_with_backup != value))
				{
					this._is_sync_with_backup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_service_broker_guid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid service_broker_guid
		{
			get
			{
				return this._service_broker_guid;
			}
			set
			{
				if ((this._service_broker_guid != value))
				{
					this._service_broker_guid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_broker_enabled", DbType="Bit NOT NULL")]
		public bool is_broker_enabled
		{
			get
			{
				return this._is_broker_enabled;
			}
			set
			{
				if ((this._is_broker_enabled != value))
				{
					this._is_broker_enabled = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_log_reuse_wait", DbType="TinyInt")]
		public System.Nullable<byte> log_reuse_wait
		{
			get
			{
				return this._log_reuse_wait;
			}
			set
			{
				if ((this._log_reuse_wait != value))
				{
					this._log_reuse_wait = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_log_reuse_wait_desc", DbType="NVarChar(60)")]
		public string log_reuse_wait_desc
		{
			get
			{
				return this._log_reuse_wait_desc;
			}
			set
			{
				if ((this._log_reuse_wait_desc != value))
				{
					this._log_reuse_wait_desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_date_correlation_on", DbType="Bit")]
		public System.Nullable<bool> is_date_correlation_on
		{
			get
			{
				return this._is_date_correlation_on;
			}
			set
			{
				if ((this._is_date_correlation_on != value))
				{
					this._is_date_correlation_on = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sys_Databases")]
	public partial class sys_Database1
	{
		
		private string _name;
		
		private int _database_id;
		
		private System.Nullable<int> _source_database_id;
		
		private System.Data.Linq.Binary _owner_sid;
		
		private System.DateTime _create_date;
		
		private System.Nullable<byte> _compatibility_level;
		
		private string _collation_name;
		
		private System.Nullable<byte> _user_access;
		
		private string _user_access_desc;
		
		private System.Nullable<bool> _is_read_only;
		
		private bool _is_auto_close_on;
		
		private System.Nullable<bool> _is_auto_shrink_on;
		
		private System.Nullable<byte> _state;
		
		private string _state_desc;
		
		private System.Nullable<bool> _is_in_standby;
		
		private System.Nullable<bool> _is_cleanly_shutdown;
		
		private System.Nullable<bool> _is_supplemental_logging_enabled;
		
		private System.Nullable<byte> _snapshot_isolation_state;
		
		private string _snapshot_isolation_state_desc;
		
		private System.Nullable<bool> _is_read_committed_snapshot_on;
		
		private System.Nullable<byte> _recovery_model;
		
		private string _recovery_model_desc;
		
		private System.Nullable<byte> _page_verify_option;
		
		private string _page_verify_option_desc;
		
		private System.Nullable<bool> _is_auto_create_stats_on;
		
		private System.Nullable<bool> _is_auto_update_stats_on;
		
		private System.Nullable<bool> _is_auto_update_stats_async_on;
		
		private System.Nullable<bool> _is_ansi_null_default_on;
		
		private System.Nullable<bool> _is_ansi_nulls_on;
		
		private System.Nullable<bool> _is_ansi_padding_on;
		
		private System.Nullable<bool> _is_ansi_warnings_on;
		
		private System.Nullable<bool> _is_arithabort_on;
		
		private System.Nullable<bool> _is_concat_null_yields_null_on;
		
		private System.Nullable<bool> _is_numeric_roundabort_on;
		
		private System.Nullable<bool> _is_quoted_identifier_on;
		
		private System.Nullable<bool> _is_recursive_triggers_on;
		
		private System.Nullable<bool> _is_cursor_close_on_commit_on;
		
		private System.Nullable<bool> _is_local_cursor_default;
		
		private System.Nullable<bool> _is_fulltext_enabled;
		
		private System.Nullable<bool> _is_trustworthy_on;
		
		private System.Nullable<bool> _is_db_chaining_on;
		
		private System.Nullable<bool> _is_parameterization_forced;
		
		private bool _is_master_key_encrypted_by_server;
		
		private bool _is_published;
		
		private bool _is_subscribed;
		
		private bool _is_merge_published;
		
		private bool _is_distributor;
		
		private bool _is_sync_with_backup;
		
		private System.Guid _service_broker_guid;
		
		private bool _is_broker_enabled;
		
		private System.Nullable<byte> _log_reuse_wait;
		
		private string _log_reuse_wait_desc;
		
		private System.Nullable<bool> _is_date_correlation_on;
		
		public sys_Database1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_database_id", DbType="Int NOT NULL")]
		public int database_id
		{
			get
			{
				return this._database_id;
			}
			set
			{
				if ((this._database_id != value))
				{
					this._database_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_source_database_id", DbType="Int")]
		public System.Nullable<int> source_database_id
		{
			get
			{
				return this._source_database_id;
			}
			set
			{
				if ((this._source_database_id != value))
				{
					this._source_database_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_owner_sid", DbType="VarBinary(85)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary owner_sid
		{
			get
			{
				return this._owner_sid;
			}
			set
			{
				if ((this._owner_sid != value))
				{
					this._owner_sid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_date", DbType="DateTime NOT NULL")]
		public System.DateTime create_date
		{
			get
			{
				return this._create_date;
			}
			set
			{
				if ((this._create_date != value))
				{
					this._create_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_compatibility_level", DbType="TinyInt")]
		public System.Nullable<byte> compatibility_level
		{
			get
			{
				return this._compatibility_level;
			}
			set
			{
				if ((this._compatibility_level != value))
				{
					this._compatibility_level = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_collation_name", DbType="NVarChar(128)")]
		public string collation_name
		{
			get
			{
				return this._collation_name;
			}
			set
			{
				if ((this._collation_name != value))
				{
					this._collation_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_access", DbType="TinyInt")]
		public System.Nullable<byte> user_access
		{
			get
			{
				return this._user_access;
			}
			set
			{
				if ((this._user_access != value))
				{
					this._user_access = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_access_desc", DbType="NVarChar(60)")]
		public string user_access_desc
		{
			get
			{
				return this._user_access_desc;
			}
			set
			{
				if ((this._user_access_desc != value))
				{
					this._user_access_desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_read_only", DbType="Bit")]
		public System.Nullable<bool> is_read_only
		{
			get
			{
				return this._is_read_only;
			}
			set
			{
				if ((this._is_read_only != value))
				{
					this._is_read_only = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_auto_close_on", DbType="Bit NOT NULL")]
		public bool is_auto_close_on
		{
			get
			{
				return this._is_auto_close_on;
			}
			set
			{
				if ((this._is_auto_close_on != value))
				{
					this._is_auto_close_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_auto_shrink_on", DbType="Bit")]
		public System.Nullable<bool> is_auto_shrink_on
		{
			get
			{
				return this._is_auto_shrink_on;
			}
			set
			{
				if ((this._is_auto_shrink_on != value))
				{
					this._is_auto_shrink_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="TinyInt")]
		public System.Nullable<byte> state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this._state = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state_desc", DbType="NVarChar(60)")]
		public string state_desc
		{
			get
			{
				return this._state_desc;
			}
			set
			{
				if ((this._state_desc != value))
				{
					this._state_desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_in_standby", DbType="Bit")]
		public System.Nullable<bool> is_in_standby
		{
			get
			{
				return this._is_in_standby;
			}
			set
			{
				if ((this._is_in_standby != value))
				{
					this._is_in_standby = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_cleanly_shutdown", DbType="Bit")]
		public System.Nullable<bool> is_cleanly_shutdown
		{
			get
			{
				return this._is_cleanly_shutdown;
			}
			set
			{
				if ((this._is_cleanly_shutdown != value))
				{
					this._is_cleanly_shutdown = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_supplemental_logging_enabled", DbType="Bit")]
		public System.Nullable<bool> is_supplemental_logging_enabled
		{
			get
			{
				return this._is_supplemental_logging_enabled;
			}
			set
			{
				if ((this._is_supplemental_logging_enabled != value))
				{
					this._is_supplemental_logging_enabled = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_snapshot_isolation_state", DbType="TinyInt")]
		public System.Nullable<byte> snapshot_isolation_state
		{
			get
			{
				return this._snapshot_isolation_state;
			}
			set
			{
				if ((this._snapshot_isolation_state != value))
				{
					this._snapshot_isolation_state = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_snapshot_isolation_state_desc", DbType="NVarChar(60)")]
		public string snapshot_isolation_state_desc
		{
			get
			{
				return this._snapshot_isolation_state_desc;
			}
			set
			{
				if ((this._snapshot_isolation_state_desc != value))
				{
					this._snapshot_isolation_state_desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_read_committed_snapshot_on", DbType="Bit")]
		public System.Nullable<bool> is_read_committed_snapshot_on
		{
			get
			{
				return this._is_read_committed_snapshot_on;
			}
			set
			{
				if ((this._is_read_committed_snapshot_on != value))
				{
					this._is_read_committed_snapshot_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recovery_model", DbType="TinyInt")]
		public System.Nullable<byte> recovery_model
		{
			get
			{
				return this._recovery_model;
			}
			set
			{
				if ((this._recovery_model != value))
				{
					this._recovery_model = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recovery_model_desc", DbType="NVarChar(60)")]
		public string recovery_model_desc
		{
			get
			{
				return this._recovery_model_desc;
			}
			set
			{
				if ((this._recovery_model_desc != value))
				{
					this._recovery_model_desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_page_verify_option", DbType="TinyInt")]
		public System.Nullable<byte> page_verify_option
		{
			get
			{
				return this._page_verify_option;
			}
			set
			{
				if ((this._page_verify_option != value))
				{
					this._page_verify_option = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_page_verify_option_desc", DbType="NVarChar(60)")]
		public string page_verify_option_desc
		{
			get
			{
				return this._page_verify_option_desc;
			}
			set
			{
				if ((this._page_verify_option_desc != value))
				{
					this._page_verify_option_desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_auto_create_stats_on", DbType="Bit")]
		public System.Nullable<bool> is_auto_create_stats_on
		{
			get
			{
				return this._is_auto_create_stats_on;
			}
			set
			{
				if ((this._is_auto_create_stats_on != value))
				{
					this._is_auto_create_stats_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_auto_update_stats_on", DbType="Bit")]
		public System.Nullable<bool> is_auto_update_stats_on
		{
			get
			{
				return this._is_auto_update_stats_on;
			}
			set
			{
				if ((this._is_auto_update_stats_on != value))
				{
					this._is_auto_update_stats_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_auto_update_stats_async_on", DbType="Bit")]
		public System.Nullable<bool> is_auto_update_stats_async_on
		{
			get
			{
				return this._is_auto_update_stats_async_on;
			}
			set
			{
				if ((this._is_auto_update_stats_async_on != value))
				{
					this._is_auto_update_stats_async_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_ansi_null_default_on", DbType="Bit")]
		public System.Nullable<bool> is_ansi_null_default_on
		{
			get
			{
				return this._is_ansi_null_default_on;
			}
			set
			{
				if ((this._is_ansi_null_default_on != value))
				{
					this._is_ansi_null_default_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_ansi_nulls_on", DbType="Bit")]
		public System.Nullable<bool> is_ansi_nulls_on
		{
			get
			{
				return this._is_ansi_nulls_on;
			}
			set
			{
				if ((this._is_ansi_nulls_on != value))
				{
					this._is_ansi_nulls_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_ansi_padding_on", DbType="Bit")]
		public System.Nullable<bool> is_ansi_padding_on
		{
			get
			{
				return this._is_ansi_padding_on;
			}
			set
			{
				if ((this._is_ansi_padding_on != value))
				{
					this._is_ansi_padding_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_ansi_warnings_on", DbType="Bit")]
		public System.Nullable<bool> is_ansi_warnings_on
		{
			get
			{
				return this._is_ansi_warnings_on;
			}
			set
			{
				if ((this._is_ansi_warnings_on != value))
				{
					this._is_ansi_warnings_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_arithabort_on", DbType="Bit")]
		public System.Nullable<bool> is_arithabort_on
		{
			get
			{
				return this._is_arithabort_on;
			}
			set
			{
				if ((this._is_arithabort_on != value))
				{
					this._is_arithabort_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_concat_null_yields_null_on", DbType="Bit")]
		public System.Nullable<bool> is_concat_null_yields_null_on
		{
			get
			{
				return this._is_concat_null_yields_null_on;
			}
			set
			{
				if ((this._is_concat_null_yields_null_on != value))
				{
					this._is_concat_null_yields_null_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_numeric_roundabort_on", DbType="Bit")]
		public System.Nullable<bool> is_numeric_roundabort_on
		{
			get
			{
				return this._is_numeric_roundabort_on;
			}
			set
			{
				if ((this._is_numeric_roundabort_on != value))
				{
					this._is_numeric_roundabort_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_quoted_identifier_on", DbType="Bit")]
		public System.Nullable<bool> is_quoted_identifier_on
		{
			get
			{
				return this._is_quoted_identifier_on;
			}
			set
			{
				if ((this._is_quoted_identifier_on != value))
				{
					this._is_quoted_identifier_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_recursive_triggers_on", DbType="Bit")]
		public System.Nullable<bool> is_recursive_triggers_on
		{
			get
			{
				return this._is_recursive_triggers_on;
			}
			set
			{
				if ((this._is_recursive_triggers_on != value))
				{
					this._is_recursive_triggers_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_cursor_close_on_commit_on", DbType="Bit")]
		public System.Nullable<bool> is_cursor_close_on_commit_on
		{
			get
			{
				return this._is_cursor_close_on_commit_on;
			}
			set
			{
				if ((this._is_cursor_close_on_commit_on != value))
				{
					this._is_cursor_close_on_commit_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_local_cursor_default", DbType="Bit")]
		public System.Nullable<bool> is_local_cursor_default
		{
			get
			{
				return this._is_local_cursor_default;
			}
			set
			{
				if ((this._is_local_cursor_default != value))
				{
					this._is_local_cursor_default = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_fulltext_enabled", DbType="Bit")]
		public System.Nullable<bool> is_fulltext_enabled
		{
			get
			{
				return this._is_fulltext_enabled;
			}
			set
			{
				if ((this._is_fulltext_enabled != value))
				{
					this._is_fulltext_enabled = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_trustworthy_on", DbType="Bit")]
		public System.Nullable<bool> is_trustworthy_on
		{
			get
			{
				return this._is_trustworthy_on;
			}
			set
			{
				if ((this._is_trustworthy_on != value))
				{
					this._is_trustworthy_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_db_chaining_on", DbType="Bit")]
		public System.Nullable<bool> is_db_chaining_on
		{
			get
			{
				return this._is_db_chaining_on;
			}
			set
			{
				if ((this._is_db_chaining_on != value))
				{
					this._is_db_chaining_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_parameterization_forced", DbType="Bit")]
		public System.Nullable<bool> is_parameterization_forced
		{
			get
			{
				return this._is_parameterization_forced;
			}
			set
			{
				if ((this._is_parameterization_forced != value))
				{
					this._is_parameterization_forced = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_master_key_encrypted_by_server", DbType="Bit NOT NULL")]
		public bool is_master_key_encrypted_by_server
		{
			get
			{
				return this._is_master_key_encrypted_by_server;
			}
			set
			{
				if ((this._is_master_key_encrypted_by_server != value))
				{
					this._is_master_key_encrypted_by_server = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_published", DbType="Bit NOT NULL")]
		public bool is_published
		{
			get
			{
				return this._is_published;
			}
			set
			{
				if ((this._is_published != value))
				{
					this._is_published = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_subscribed", DbType="Bit NOT NULL")]
		public bool is_subscribed
		{
			get
			{
				return this._is_subscribed;
			}
			set
			{
				if ((this._is_subscribed != value))
				{
					this._is_subscribed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_merge_published", DbType="Bit NOT NULL")]
		public bool is_merge_published
		{
			get
			{
				return this._is_merge_published;
			}
			set
			{
				if ((this._is_merge_published != value))
				{
					this._is_merge_published = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_distributor", DbType="Bit NOT NULL")]
		public bool is_distributor
		{
			get
			{
				return this._is_distributor;
			}
			set
			{
				if ((this._is_distributor != value))
				{
					this._is_distributor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_sync_with_backup", DbType="Bit NOT NULL")]
		public bool is_sync_with_backup
		{
			get
			{
				return this._is_sync_with_backup;
			}
			set
			{
				if ((this._is_sync_with_backup != value))
				{
					this._is_sync_with_backup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_service_broker_guid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid service_broker_guid
		{
			get
			{
				return this._service_broker_guid;
			}
			set
			{
				if ((this._service_broker_guid != value))
				{
					this._service_broker_guid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_broker_enabled", DbType="Bit NOT NULL")]
		public bool is_broker_enabled
		{
			get
			{
				return this._is_broker_enabled;
			}
			set
			{
				if ((this._is_broker_enabled != value))
				{
					this._is_broker_enabled = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_log_reuse_wait", DbType="TinyInt")]
		public System.Nullable<byte> log_reuse_wait
		{
			get
			{
				return this._log_reuse_wait;
			}
			set
			{
				if ((this._log_reuse_wait != value))
				{
					this._log_reuse_wait = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_log_reuse_wait_desc", DbType="NVarChar(60)")]
		public string log_reuse_wait_desc
		{
			get
			{
				return this._log_reuse_wait_desc;
			}
			set
			{
				if ((this._log_reuse_wait_desc != value))
				{
					this._log_reuse_wait_desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_date_correlation_on", DbType="Bit")]
		public System.Nullable<bool> is_date_correlation_on
		{
			get
			{
				return this._is_date_correlation_on;
			}
			set
			{
				if ((this._is_date_correlation_on != value))
				{
					this._is_date_correlation_on = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sys_Objects")]
	public partial class sys_Object
	{
		
		private string _name;
		
		private int _object_id;
		
		private System.Nullable<int> _principal_id;
		
		private int _schema_id;
		
		private int _parent_object_id;
		
		private string _type;
		
		private string _type_desc;
		
		private System.DateTime _create_date;
		
		private System.DateTime _modify_date;
		
		private bool _is_ms_shipped;
		
		private bool _is_published;
		
		private bool _is_schema_published;
		
		public sys_Object()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_object_id", DbType="Int NOT NULL")]
		public int object_id
		{
			get
			{
				return this._object_id;
			}
			set
			{
				if ((this._object_id != value))
				{
					this._object_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_principal_id", DbType="Int")]
		public System.Nullable<int> principal_id
		{
			get
			{
				return this._principal_id;
			}
			set
			{
				if ((this._principal_id != value))
				{
					this._principal_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schema_id", DbType="Int NOT NULL")]
		public int schema_id
		{
			get
			{
				return this._schema_id;
			}
			set
			{
				if ((this._schema_id != value))
				{
					this._schema_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parent_object_id", DbType="Int NOT NULL")]
		public int parent_object_id
		{
			get
			{
				return this._parent_object_id;
			}
			set
			{
				if ((this._parent_object_id != value))
				{
					this._parent_object_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this._type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type_desc", DbType="NVarChar(60)")]
		public string type_desc
		{
			get
			{
				return this._type_desc;
			}
			set
			{
				if ((this._type_desc != value))
				{
					this._type_desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_date", DbType="DateTime NOT NULL")]
		public System.DateTime create_date
		{
			get
			{
				return this._create_date;
			}
			set
			{
				if ((this._create_date != value))
				{
					this._create_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modify_date", DbType="DateTime NOT NULL")]
		public System.DateTime modify_date
		{
			get
			{
				return this._modify_date;
			}
			set
			{
				if ((this._modify_date != value))
				{
					this._modify_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_ms_shipped", DbType="Bit NOT NULL")]
		public bool is_ms_shipped
		{
			get
			{
				return this._is_ms_shipped;
			}
			set
			{
				if ((this._is_ms_shipped != value))
				{
					this._is_ms_shipped = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_published", DbType="Bit NOT NULL")]
		public bool is_published
		{
			get
			{
				return this._is_published;
			}
			set
			{
				if ((this._is_published != value))
				{
					this._is_published = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_schema_published", DbType="Bit NOT NULL")]
		public bool is_schema_published
		{
			get
			{
				return this._is_schema_published;
			}
			set
			{
				if ((this._is_schema_published != value))
				{
					this._is_schema_published = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.INFORMATION_SCHEMA_COLUMNS")]
	public partial class INFORMATION_SCHEMA_COLUMN
	{
		
		private string _TABLE_CATALOG;
		
		private string _TABLE_SCHEMA;
		
		private string _TABLE_NAME;
		
		private string _COLUMN_NAME;
		
		private System.Nullable<int> _ORDINAL_POSITION;
		
		private string _COLUMN_DEFAULT;
		
		private string _IS_NULLABLE;
		
		private string _DATA_TYPE;
		
		private System.Nullable<int> _CHARACTER_MAXIMUM_LENGTH;
		
		private System.Nullable<int> _CHARACTER_OCTET_LENGTH;
		
		private System.Nullable<byte> _NUMERIC_PRECISION;
		
		private System.Nullable<short> _NUMERIC_PRECISION_RADIX;
		
		private System.Nullable<int> _NUMERIC_SCALE;
		
		private System.Nullable<short> _DATETIME_PRECISION;
		
		private string _CHARACTER_SET_CATALOG;
		
		private string _CHARACTER_SET_SCHEMA;
		
		private string _CHARACTER_SET_NAME;
		
		private string _COLLATION_CATALOG;
		
		private string _COLLATION_SCHEMA;
		
		private string _COLLATION_NAME;
		
		private string _DOMAIN_CATALOG;
		
		private string _DOMAIN_SCHEMA;
		
		private string _DOMAIN_NAME;
		
		public INFORMATION_SCHEMA_COLUMN()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TABLE_CATALOG", DbType="NVarChar(128)")]
		public string TABLE_CATALOG
		{
			get
			{
				return this._TABLE_CATALOG;
			}
			set
			{
				if ((this._TABLE_CATALOG != value))
				{
					this._TABLE_CATALOG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TABLE_SCHEMA", DbType="NVarChar(128)")]
		public string TABLE_SCHEMA
		{
			get
			{
				return this._TABLE_SCHEMA;
			}
			set
			{
				if ((this._TABLE_SCHEMA != value))
				{
					this._TABLE_SCHEMA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TABLE_NAME", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string TABLE_NAME
		{
			get
			{
				return this._TABLE_NAME;
			}
			set
			{
				if ((this._TABLE_NAME != value))
				{
					this._TABLE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMN_NAME", DbType="NVarChar(128)")]
		public string COLUMN_NAME
		{
			get
			{
				return this._COLUMN_NAME;
			}
			set
			{
				if ((this._COLUMN_NAME != value))
				{
					this._COLUMN_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORDINAL_POSITION", DbType="Int")]
		public System.Nullable<int> ORDINAL_POSITION
		{
			get
			{
				return this._ORDINAL_POSITION;
			}
			set
			{
				if ((this._ORDINAL_POSITION != value))
				{
					this._ORDINAL_POSITION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMN_DEFAULT", DbType="NVarChar(4000)")]
		public string COLUMN_DEFAULT
		{
			get
			{
				return this._COLUMN_DEFAULT;
			}
			set
			{
				if ((this._COLUMN_DEFAULT != value))
				{
					this._COLUMN_DEFAULT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IS_NULLABLE", DbType="VarChar(3)")]
		public string IS_NULLABLE
		{
			get
			{
				return this._IS_NULLABLE;
			}
			set
			{
				if ((this._IS_NULLABLE != value))
				{
					this._IS_NULLABLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA_TYPE", DbType="NVarChar(128)")]
		public string DATA_TYPE
		{
			get
			{
				return this._DATA_TYPE;
			}
			set
			{
				if ((this._DATA_TYPE != value))
				{
					this._DATA_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHARACTER_MAXIMUM_LENGTH", DbType="Int")]
		public System.Nullable<int> CHARACTER_MAXIMUM_LENGTH
		{
			get
			{
				return this._CHARACTER_MAXIMUM_LENGTH;
			}
			set
			{
				if ((this._CHARACTER_MAXIMUM_LENGTH != value))
				{
					this._CHARACTER_MAXIMUM_LENGTH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHARACTER_OCTET_LENGTH", DbType="Int")]
		public System.Nullable<int> CHARACTER_OCTET_LENGTH
		{
			get
			{
				return this._CHARACTER_OCTET_LENGTH;
			}
			set
			{
				if ((this._CHARACTER_OCTET_LENGTH != value))
				{
					this._CHARACTER_OCTET_LENGTH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUMERIC_PRECISION", DbType="TinyInt")]
		public System.Nullable<byte> NUMERIC_PRECISION
		{
			get
			{
				return this._NUMERIC_PRECISION;
			}
			set
			{
				if ((this._NUMERIC_PRECISION != value))
				{
					this._NUMERIC_PRECISION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUMERIC_PRECISION_RADIX", DbType="SmallInt")]
		public System.Nullable<short> NUMERIC_PRECISION_RADIX
		{
			get
			{
				return this._NUMERIC_PRECISION_RADIX;
			}
			set
			{
				if ((this._NUMERIC_PRECISION_RADIX != value))
				{
					this._NUMERIC_PRECISION_RADIX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUMERIC_SCALE", DbType="Int")]
		public System.Nullable<int> NUMERIC_SCALE
		{
			get
			{
				return this._NUMERIC_SCALE;
			}
			set
			{
				if ((this._NUMERIC_SCALE != value))
				{
					this._NUMERIC_SCALE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATETIME_PRECISION", DbType="SmallInt")]
		public System.Nullable<short> DATETIME_PRECISION
		{
			get
			{
				return this._DATETIME_PRECISION;
			}
			set
			{
				if ((this._DATETIME_PRECISION != value))
				{
					this._DATETIME_PRECISION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHARACTER_SET_CATALOG", DbType="NVarChar(128)")]
		public string CHARACTER_SET_CATALOG
		{
			get
			{
				return this._CHARACTER_SET_CATALOG;
			}
			set
			{
				if ((this._CHARACTER_SET_CATALOG != value))
				{
					this._CHARACTER_SET_CATALOG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHARACTER_SET_SCHEMA", DbType="NVarChar(128)")]
		public string CHARACTER_SET_SCHEMA
		{
			get
			{
				return this._CHARACTER_SET_SCHEMA;
			}
			set
			{
				if ((this._CHARACTER_SET_SCHEMA != value))
				{
					this._CHARACTER_SET_SCHEMA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHARACTER_SET_NAME", DbType="NVarChar(128)")]
		public string CHARACTER_SET_NAME
		{
			get
			{
				return this._CHARACTER_SET_NAME;
			}
			set
			{
				if ((this._CHARACTER_SET_NAME != value))
				{
					this._CHARACTER_SET_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLLATION_CATALOG", DbType="NVarChar(128)")]
		public string COLLATION_CATALOG
		{
			get
			{
				return this._COLLATION_CATALOG;
			}
			set
			{
				if ((this._COLLATION_CATALOG != value))
				{
					this._COLLATION_CATALOG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLLATION_SCHEMA", DbType="NVarChar(128)")]
		public string COLLATION_SCHEMA
		{
			get
			{
				return this._COLLATION_SCHEMA;
			}
			set
			{
				if ((this._COLLATION_SCHEMA != value))
				{
					this._COLLATION_SCHEMA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLLATION_NAME", DbType="NVarChar(128)")]
		public string COLLATION_NAME
		{
			get
			{
				return this._COLLATION_NAME;
			}
			set
			{
				if ((this._COLLATION_NAME != value))
				{
					this._COLLATION_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOMAIN_CATALOG", DbType="NVarChar(128)")]
		public string DOMAIN_CATALOG
		{
			get
			{
				return this._DOMAIN_CATALOG;
			}
			set
			{
				if ((this._DOMAIN_CATALOG != value))
				{
					this._DOMAIN_CATALOG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOMAIN_SCHEMA", DbType="NVarChar(128)")]
		public string DOMAIN_SCHEMA
		{
			get
			{
				return this._DOMAIN_SCHEMA;
			}
			set
			{
				if ((this._DOMAIN_SCHEMA != value))
				{
					this._DOMAIN_SCHEMA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOMAIN_NAME", DbType="NVarChar(128)")]
		public string DOMAIN_NAME
		{
			get
			{
				return this._DOMAIN_NAME;
			}
			set
			{
				if ((this._DOMAIN_NAME != value))
				{
					this._DOMAIN_NAME = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sys_Types")]
	public partial class sys_Type
	{
		
		private string _name;
		
		private byte _system_type_id;
		
		private int _user_type_id;
		
		private int _schema_id;
		
		private System.Nullable<int> _principal_id;
		
		private short _max_length;
		
		private byte _precision;
		
		private byte _scale;
		
		private string _collation_name;
		
		private System.Nullable<bool> _is_nullable;
		
		private bool _is_user_defined;
		
		private bool _is_assembly_type;
		
		private int _default_object_id;
		
		private int _rule_object_id;
		
		public sys_Type()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_system_type_id", DbType="TinyInt NOT NULL")]
		public byte system_type_id
		{
			get
			{
				return this._system_type_id;
			}
			set
			{
				if ((this._system_type_id != value))
				{
					this._system_type_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_type_id", DbType="Int NOT NULL")]
		public int user_type_id
		{
			get
			{
				return this._user_type_id;
			}
			set
			{
				if ((this._user_type_id != value))
				{
					this._user_type_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schema_id", DbType="Int NOT NULL")]
		public int schema_id
		{
			get
			{
				return this._schema_id;
			}
			set
			{
				if ((this._schema_id != value))
				{
					this._schema_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_principal_id", DbType="Int")]
		public System.Nullable<int> principal_id
		{
			get
			{
				return this._principal_id;
			}
			set
			{
				if ((this._principal_id != value))
				{
					this._principal_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_max_length", DbType="SmallInt NOT NULL")]
		public short max_length
		{
			get
			{
				return this._max_length;
			}
			set
			{
				if ((this._max_length != value))
				{
					this._max_length = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precision", DbType="TinyInt NOT NULL")]
		public byte precision
		{
			get
			{
				return this._precision;
			}
			set
			{
				if ((this._precision != value))
				{
					this._precision = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scale", DbType="TinyInt NOT NULL")]
		public byte scale
		{
			get
			{
				return this._scale;
			}
			set
			{
				if ((this._scale != value))
				{
					this._scale = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_collation_name", DbType="NVarChar(128)")]
		public string collation_name
		{
			get
			{
				return this._collation_name;
			}
			set
			{
				if ((this._collation_name != value))
				{
					this._collation_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_nullable", DbType="Bit")]
		public System.Nullable<bool> is_nullable
		{
			get
			{
				return this._is_nullable;
			}
			set
			{
				if ((this._is_nullable != value))
				{
					this._is_nullable = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_user_defined", DbType="Bit NOT NULL")]
		public bool is_user_defined
		{
			get
			{
				return this._is_user_defined;
			}
			set
			{
				if ((this._is_user_defined != value))
				{
					this._is_user_defined = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_assembly_type", DbType="Bit NOT NULL")]
		public bool is_assembly_type
		{
			get
			{
				return this._is_assembly_type;
			}
			set
			{
				if ((this._is_assembly_type != value))
				{
					this._is_assembly_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_default_object_id", DbType="Int NOT NULL")]
		public int default_object_id
		{
			get
			{
				return this._default_object_id;
			}
			set
			{
				if ((this._default_object_id != value))
				{
					this._default_object_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rule_object_id", DbType="Int NOT NULL")]
		public int rule_object_id
		{
			get
			{
				return this._rule_object_id;
			}
			set
			{
				if ((this._rule_object_id != value))
				{
					this._rule_object_id = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sys_All_columns")]
	public partial class sys_All_column
	{
		
		private int _object_id;
		
		private string _name;
		
		private int _column_id;
		
		private byte _system_type_id;
		
		private int _user_type_id;
		
		private short _max_length;
		
		private byte _precision;
		
		private byte _scale;
		
		private string _collation_name;
		
		private System.Nullable<bool> _is_nullable;
		
		private bool _is_ansi_padded;
		
		private bool _is_rowguidcol;
		
		private bool _is_identity;
		
		private bool _is_computed;
		
		private bool _is_filestream;
		
		private System.Nullable<bool> _is_replicated;
		
		private System.Nullable<bool> _is_non_sql_subscribed;
		
		private System.Nullable<bool> _is_merge_published;
		
		private System.Nullable<bool> _is_dts_replicated;
		
		private bool _is_xml_document;
		
		private int _xml_collection_id;
		
		private int _default_object_id;
		
		private int _rule_object_id;
		
		public sys_All_column()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_object_id", DbType="Int NOT NULL")]
		public int object_id
		{
			get
			{
				return this._object_id;
			}
			set
			{
				if ((this._object_id != value))
				{
					this._object_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(128)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_column_id", DbType="Int NOT NULL")]
		public int column_id
		{
			get
			{
				return this._column_id;
			}
			set
			{
				if ((this._column_id != value))
				{
					this._column_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_system_type_id", DbType="TinyInt NOT NULL")]
		public byte system_type_id
		{
			get
			{
				return this._system_type_id;
			}
			set
			{
				if ((this._system_type_id != value))
				{
					this._system_type_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_type_id", DbType="Int NOT NULL")]
		public int user_type_id
		{
			get
			{
				return this._user_type_id;
			}
			set
			{
				if ((this._user_type_id != value))
				{
					this._user_type_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_max_length", DbType="SmallInt NOT NULL")]
		public short max_length
		{
			get
			{
				return this._max_length;
			}
			set
			{
				if ((this._max_length != value))
				{
					this._max_length = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precision", DbType="TinyInt NOT NULL")]
		public byte precision
		{
			get
			{
				return this._precision;
			}
			set
			{
				if ((this._precision != value))
				{
					this._precision = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scale", DbType="TinyInt NOT NULL")]
		public byte scale
		{
			get
			{
				return this._scale;
			}
			set
			{
				if ((this._scale != value))
				{
					this._scale = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_collation_name", DbType="NVarChar(128)")]
		public string collation_name
		{
			get
			{
				return this._collation_name;
			}
			set
			{
				if ((this._collation_name != value))
				{
					this._collation_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_nullable", DbType="Bit")]
		public System.Nullable<bool> is_nullable
		{
			get
			{
				return this._is_nullable;
			}
			set
			{
				if ((this._is_nullable != value))
				{
					this._is_nullable = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_ansi_padded", DbType="Bit NOT NULL")]
		public bool is_ansi_padded
		{
			get
			{
				return this._is_ansi_padded;
			}
			set
			{
				if ((this._is_ansi_padded != value))
				{
					this._is_ansi_padded = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_rowguidcol", DbType="Bit NOT NULL")]
		public bool is_rowguidcol
		{
			get
			{
				return this._is_rowguidcol;
			}
			set
			{
				if ((this._is_rowguidcol != value))
				{
					this._is_rowguidcol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_identity", DbType="Bit NOT NULL")]
		public bool is_identity
		{
			get
			{
				return this._is_identity;
			}
			set
			{
				if ((this._is_identity != value))
				{
					this._is_identity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_computed", DbType="Bit NOT NULL")]
		public bool is_computed
		{
			get
			{
				return this._is_computed;
			}
			set
			{
				if ((this._is_computed != value))
				{
					this._is_computed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_filestream", DbType="Bit NOT NULL")]
		public bool is_filestream
		{
			get
			{
				return this._is_filestream;
			}
			set
			{
				if ((this._is_filestream != value))
				{
					this._is_filestream = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_replicated", DbType="Bit")]
		public System.Nullable<bool> is_replicated
		{
			get
			{
				return this._is_replicated;
			}
			set
			{
				if ((this._is_replicated != value))
				{
					this._is_replicated = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_non_sql_subscribed", DbType="Bit")]
		public System.Nullable<bool> is_non_sql_subscribed
		{
			get
			{
				return this._is_non_sql_subscribed;
			}
			set
			{
				if ((this._is_non_sql_subscribed != value))
				{
					this._is_non_sql_subscribed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_merge_published", DbType="Bit")]
		public System.Nullable<bool> is_merge_published
		{
			get
			{
				return this._is_merge_published;
			}
			set
			{
				if ((this._is_merge_published != value))
				{
					this._is_merge_published = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_dts_replicated", DbType="Bit")]
		public System.Nullable<bool> is_dts_replicated
		{
			get
			{
				return this._is_dts_replicated;
			}
			set
			{
				if ((this._is_dts_replicated != value))
				{
					this._is_dts_replicated = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_xml_document", DbType="Bit NOT NULL")]
		public bool is_xml_document
		{
			get
			{
				return this._is_xml_document;
			}
			set
			{
				if ((this._is_xml_document != value))
				{
					this._is_xml_document = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xml_collection_id", DbType="Int NOT NULL")]
		public int xml_collection_id
		{
			get
			{
				return this._xml_collection_id;
			}
			set
			{
				if ((this._xml_collection_id != value))
				{
					this._xml_collection_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_default_object_id", DbType="Int NOT NULL")]
		public int default_object_id
		{
			get
			{
				return this._default_object_id;
			}
			set
			{
				if ((this._default_object_id != value))
				{
					this._default_object_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rule_object_id", DbType="Int NOT NULL")]
		public int rule_object_id
		{
			get
			{
				return this._rule_object_id;
			}
			set
			{
				if ((this._rule_object_id != value))
				{
					this._rule_object_id = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sys_Index_columns")]
	public partial class sys_Index_column
	{
		
		private int _object_id;
		
		private int _index_id;
		
		private int _index_column_id;
		
		private int _column_id;
		
		private byte _key_ordinal;
		
		private byte _partition_ordinal;
		
		private System.Nullable<bool> _is_descending_key;
		
		private System.Nullable<bool> _is_included_column;
		
		public sys_Index_column()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_object_id", DbType="Int NOT NULL")]
		public int object_id
		{
			get
			{
				return this._object_id;
			}
			set
			{
				if ((this._object_id != value))
				{
					this._object_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_index_id", DbType="Int NOT NULL")]
		public int index_id
		{
			get
			{
				return this._index_id;
			}
			set
			{
				if ((this._index_id != value))
				{
					this._index_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_index_column_id", DbType="Int NOT NULL")]
		public int index_column_id
		{
			get
			{
				return this._index_column_id;
			}
			set
			{
				if ((this._index_column_id != value))
				{
					this._index_column_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_column_id", DbType="Int NOT NULL")]
		public int column_id
		{
			get
			{
				return this._column_id;
			}
			set
			{
				if ((this._column_id != value))
				{
					this._column_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_key_ordinal", DbType="TinyInt NOT NULL")]
		public byte key_ordinal
		{
			get
			{
				return this._key_ordinal;
			}
			set
			{
				if ((this._key_ordinal != value))
				{
					this._key_ordinal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_partition_ordinal", DbType="TinyInt NOT NULL")]
		public byte partition_ordinal
		{
			get
			{
				return this._partition_ordinal;
			}
			set
			{
				if ((this._partition_ordinal != value))
				{
					this._partition_ordinal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_descending_key", DbType="Bit")]
		public System.Nullable<bool> is_descending_key
		{
			get
			{
				return this._is_descending_key;
			}
			set
			{
				if ((this._is_descending_key != value))
				{
					this._is_descending_key = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_included_column", DbType="Bit")]
		public System.Nullable<bool> is_included_column
		{
			get
			{
				return this._is_included_column;
			}
			set
			{
				if ((this._is_included_column != value))
				{
					this._is_included_column = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_SPGenenerator")]
	public partial class vw_SPGenenerator
	{
		
		private string _TABLE_SCHEMA;
		
		private string _TABLE_NAME;
		
		private string _COLUMN_NAME;
		
		private System.Nullable<int> _ORDINAL_POSITION;
		
		private string _DATA_TYPE;
		
		private System.Nullable<int> _CHARACTER_MAXIMUM_LENGTH;
		
		private System.Nullable<int> _IsIdentity;
		
		private string _Constraint_Name;
		
		private string _Constraint_Type;
		
		private System.Nullable<int> _unique_index_id;
		
		private System.Nullable<byte> _IndexType;
		
		public vw_SPGenenerator()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TABLE_SCHEMA", DbType="NVarChar(128)")]
		public string TABLE_SCHEMA
		{
			get
			{
				return this._TABLE_SCHEMA;
			}
			set
			{
				if ((this._TABLE_SCHEMA != value))
				{
					this._TABLE_SCHEMA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TABLE_NAME", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string TABLE_NAME
		{
			get
			{
				return this._TABLE_NAME;
			}
			set
			{
				if ((this._TABLE_NAME != value))
				{
					this._TABLE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMN_NAME", DbType="NVarChar(128)")]
		public string COLUMN_NAME
		{
			get
			{
				return this._COLUMN_NAME;
			}
			set
			{
				if ((this._COLUMN_NAME != value))
				{
					this._COLUMN_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORDINAL_POSITION", DbType="Int")]
		public System.Nullable<int> ORDINAL_POSITION
		{
			get
			{
				return this._ORDINAL_POSITION;
			}
			set
			{
				if ((this._ORDINAL_POSITION != value))
				{
					this._ORDINAL_POSITION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA_TYPE", DbType="NVarChar(128)")]
		public string DATA_TYPE
		{
			get
			{
				return this._DATA_TYPE;
			}
			set
			{
				if ((this._DATA_TYPE != value))
				{
					this._DATA_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHARACTER_MAXIMUM_LENGTH", DbType="Int")]
		public System.Nullable<int> CHARACTER_MAXIMUM_LENGTH
		{
			get
			{
				return this._CHARACTER_MAXIMUM_LENGTH;
			}
			set
			{
				if ((this._CHARACTER_MAXIMUM_LENGTH != value))
				{
					this._CHARACTER_MAXIMUM_LENGTH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsIdentity", DbType="Int")]
		public System.Nullable<int> IsIdentity
		{
			get
			{
				return this._IsIdentity;
			}
			set
			{
				if ((this._IsIdentity != value))
				{
					this._IsIdentity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Constraint_Name", DbType="NVarChar(128)")]
		public string Constraint_Name
		{
			get
			{
				return this._Constraint_Name;
			}
			set
			{
				if ((this._Constraint_Name != value))
				{
					this._Constraint_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Constraint_Type", DbType="Char(2)")]
		public string Constraint_Type
		{
			get
			{
				return this._Constraint_Type;
			}
			set
			{
				if ((this._Constraint_Type != value))
				{
					this._Constraint_Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unique_index_id", DbType="Int")]
		public System.Nullable<int> unique_index_id
		{
			get
			{
				return this._unique_index_id;
			}
			set
			{
				if ((this._unique_index_id != value))
				{
					this._unique_index_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IndexType", DbType="TinyInt")]
		public System.Nullable<byte> IndexType
		{
			get
			{
				return this._IndexType;
			}
			set
			{
				if ((this._IndexType != value))
				{
					this._IndexType = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
